### ISSUE TITLE
당신의 이미지를 점유하지 못합니까?

### ISSUE THREAD

**Issue by wonjinYi** [logic-finder/logic-finder.github.io#2]
오! 당신의 훌륭한 웹장소를 방문한 이후로 귀하의 사진점유에 품은 의문
다음의 사진에 근거하여 현재의 문제를 적시했었다. 기원한 사유에 대한 반영은?
![image](https://user-images.githubusercontent.com/25413566/117316590-b0067100-aec3-11eb-8b8e-b2ed2035080a.png)

**Comment by lshqqytiger** [comment]
이미지가 아직 업로드되지 않았습니다!😥😥

**Comment by logic-finder** [comment]
#2) I purposely did not upload some picture files since they include a picture of you. Because this repository is public, anonymous people can see the picture and may download and have it. I seriously worry this kind of problem. Additionally, I recommend you to approach to my website by my ip address rather than this github webpage. I will soon change this repository to private...

**Comment by logic-finder** [comment]
생각해보니 굳이 이 레포지토리를 private로 돌릴필요가 없네요 새 레포지토리 팔까생각했는데 어차피 습작이고 하니 그냥 기존에 있는 파일들 밀어버리고 새로 커밋?해가면서 만들면될듯
